### ISSUE TITLE
Support Light & Dark Mode

### ISSUE THREAD

**Issue by Spikeysanju** [Spikeysanju/JetQuotes#11]
### Proposed Change

- Support for Light/Dark mode using **_`Datastore`_**
- This change is to encourage the participants of **_`Hacktoberfest 2020`_** for the this events

### Reference

_**`Datastore`**_ -  https://developer.android.com/topic/libraries/architecture/datastore

**Comment by kriticalflare** [comment]
Hey @Spikeysanju 👋, i would like to take a stab at this issue. I see the current dark mode implementation depends on DataStore. Would the new user facing toggle replace the current implementation completely?

**Comment by Spikeysanju** [comment]
Yes your right. It will be great if we can have light bulb on the top to turn on and off the dark mode using Datastore.

I'm attaching the design for reference 👍


![Screenshot_2020-10-01-15-29-18-308_com.android.chrome.jpg](https://user-images.githubusercontent.com/23400022/94795378-e2fef880-03fa-11eb-8497-2fcb4bd93b52.jpg)

**Comment by Spikeysanju** [comment]
@kriticalflare You have done a great job. Thanks for the contribution 👍

**Comment by kriticalflare** [comment]
Thanks @Spikeysanju 🙌
