### ISSUE TITLE
Update to Compose Navigation

### ISSUE THREAD

**Issue by Spikeysanju** [Spikeysanju/JetQuotes#50]

**Comment by Rajnish23** [comment]
Hi, Should I work on this?

**Comment by Spikeysanju** [comment]
@Rajnish23 Yes buddy you can 👍

**Comment by Rajnish23** [comment]
Thanks. I've started implementing the changes. I found that a lot of things in jetpack compose is being deprecated.
I've updated the gradle versions and started making changes to deprecated components. 
Is tthat okay to you, Should I continue making changes? @Spikeysanju

**Comment by Spikeysanju** [comment]
@Rajnish23 Yes buddy, You're in the direction. Please go-ahead and update the changes 👍

**Comment by Spikeysanju** [comment]
@Rajnish23  PR Merged 🎉 , Thank you so much for your contribution 👍
