### ISSUE TITLE
HELP !

### ISSUE THREAD

**Issue by Karan326** [Spikeysanju/JetQuotes#9]
Sir I also want to make such app, so could you please tell how should I proceed?
Is there any video tutorial for it or something?
Please help sir

**Comment by Spikeysanju** [comment]
Hey @Karan326  I appreciate your interest to learn. You can find various codelabs provided by google. And I'm also planning to create tutorial for this app. Stay Tuned 👉  Here is my - [YT Channel](https://www.youtube.com/channel/UC4sjtDCIHMTwWg5k1_eHiug) 

And then please don't create issues for this kind of question. You can always dm me on social media handles 🙂
